cytometry/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import FieldListView
from .views import SubFieldListView
from .views import TopicListView

urlpatterns = [
    url(r'^$', FieldListView.as_view(), name='field-list'),
    url(r'^(?P<slug>[-_\w]+)/$', SubFieldListView.as_view(), name='subfield-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)$', TopicListView.as_view(), name='topic-list'),
]

escca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

from django.contrib import admin
from django.contrib.auth.decorators import login_required

from quiz.views import PPPView
from quiz.views import ProfileView
from quiz.views import ProfileUpdateView
from quiz.views import TopicResultsView
from quiz.views import UserTopicsView
from quiz.views import ContactView

from quiz.views import IndexView

from ckeditor import views

admin.autodiscover()
admin.site.site_header = _('ESCCA administration')
admin.site.site_title = _('ESCCA site admin')

urlpatterns = [
    # Examples:
    # url(r'^$', 'escca.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileView.as_view(), name='profile'),
    url(r'^accounts/profile/topic/(?P<pk>\d+)$', TopicResultsView.as_view(), name='topic_results'),
    url(r'^accounts/profile/edit$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/topics/edit$', UserTopicsView.as_view(), name='topics_edit'),
    url(r'^accounts/profile/ppp$', PPPView.as_view(), name='ppp'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    # We must override those urls in order to make them login_required instead of staff_required
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^cytometry/', include('cytometry.urls', namespace='cytometry')),
    url(r'^directory/', include('directory.urls', namespace='directory')),
    url(r'^sponsors/', include('sponsors.urls', namespace='sponsors')),
    url(r'^lectures/', include('lectures.urls', namespace='lectures')),
    url(r'^tutorships/', include('tutorships.urls', namespace='tutorships')),
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import GeneralStatsView
from .views import StatsBySubFieldView
from .views import StatsByTopicView
from .views import StatsByQuizView
from .views import StatsByQuestionView

from .views import QuizCreateView
from .views import QuizUpdateView

from .views import QuizListView
from .views import QuizUserListView
from .views import QuizReviewListView
from .views import QuizByTopicListView
from .views import QuizDetailView
from .views import QuizTakeView
from .views import QuizResultView

from .views import QuizAskReviewView
from .views import QuizAddReviewerView
from .views import QuizPopReviewerView
from .views import QuizCommentView
from .views import QuizReviewView
from .views import QuizPublishView
from .views import QuizArchiveView

from .views import MailToUsersView

urlpatterns = [
    url(r'^$', QuizListView.as_view(), name='quiz-list'),
    url(r'^stats/$', GeneralStatsView.as_view(), name='quiz-stats'),
    url(r'^stats/by_subfield/(?P<pk>\d+)$', StatsBySubFieldView.as_view(), name='quiz-stats-by-subfield'),
    url(r'^stats/by_topic/(?P<pk>\d+)$', StatsByTopicView.as_view(), name='quiz-stats-by-topic'),
    url(r'^stats/by_quiz/(?P<pk>\d+)$', StatsByQuizView.as_view(), name='quiz-stats-by-quiz'),
    url(r'^stats/by_question/(?P<pk>\d+)$', StatsByQuestionView.as_view(), name='quiz-stats-by-question'),
    url(r'^review/$', QuizReviewListView.as_view(), name='quiz-review-list'),
    url(r'^user/$', QuizUserListView.as_view(), name='quiz-user-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)/(?P<topicslug>[-_\w]+)/$',
        QuizByTopicListView.as_view(), name='quiz-by-topic-list'),
    url(r'^create$', QuizCreateView.as_view(), name='quiz-create'),
    url(r'^(?P<pk>\d+)/$', QuizDetailView.as_view(), name='quiz-detail'),
    url(r'^(?P<pk>\d+)/update$', QuizUpdateView.as_view(), name='quiz-update'),
    url(r'^(?P<pk>\d+)/ask_review$', QuizAskReviewView.as_view(), name='quiz-ask-review'),
    url(r'^(?P<pk>\d+)/add-reviewer$', QuizAddReviewerView.as_view(), name='quiz-add-reviewer'),
    url(r'^(?P<pk>\d+)/pop-reviewer$', QuizPopReviewerView.as_view(), name='quiz-pop-reviewer'),
    url(r'^(?P<pk>\d+)/comment$', QuizCommentView.as_view(), name='quiz-comment'),
    url(r'^(?P<pk>\d+)/review$', QuizReviewView.as_view(), name='quiz-review'),
    url(r'^(?P<pk>\d+)/publish$', QuizPublishView.as_view(), name='quiz-publish'),
    url(r'^(?P<pk>\d+)/archive$', QuizArchiveView.as_view(), name='quiz-archive'),
    url(r'^(?P<pk>\d+)/take$', QuizTakeView.as_view(), name='quiz-take'),
    url(r'^(?P<pk>\d+)/result$', QuizResultView.as_view(), name='quiz-result'),
    url(r'^mail_to_users/$', MailToUsersView.as_view(), name='mail_to_users'),
]

quiz/models.py
from __future__ import division
from __future__ import unicode_literals

import datetime

from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.mail import send_mass_mail, send_mail, EmailMessage
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Sum
from django.db.models.signals import m2m_changed, post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext, ugettext_lazy as _

from ckeditor.fields import RichTextField

from django_countries.fields import CountryField

from django_fsm import FSMField, transition

from guardian.shortcuts import assign_perm, remove_perm

from model_utils.models import TimeStampedModel

from cytometry.models import Topic

from quiz.emails import QUIZ_PUBLISHED_EMAIL
from quiz.emails import CURRENT_FEES_PAYED_EMAIL
from quiz.emails import NEXT_FEES_PAYED_EMAIL
from quiz.emails import QUIZ_COMMENT_EMAIL
from quiz.emails import USER_CREATED_EMAIL


LEVEL_CHOICES = (
    ('1', _('basic')),
    ('2', _('current')),
    ('3', _('advanced')),
    ('4', _('expert')),
)


def get_current_site():
    return Site.objects.get_current()


@python_2_unicode_compatible
class Year(models.Model):
    year = models.PositiveIntegerField(_('year'))

    class Meta:
        verbose_name = _('year')

    def __str__(self):
        return str(self.year)


@python_2_unicode_compatible
class Profile(models.Model):
    user = models.OneToOneField(User)
    country = CountryField()
    city = models.CharField(_('city'), max_length=255)
    lab_name = models.CharField(_('lab name'), max_length=255, blank=True)
    lab_name_url = models.URLField(_('lab name website'), blank=True)
    accept_emails = models.BooleanField(_('I accept e-mail from ESCCA'), default=True)
    topics_of_interest = models.ManyToManyField(Topic, through='ProfileTopicsOfInterest')
    fees_payed = models.ManyToManyField(Year, blank=True)

    class Meta:
        verbose_name = _('profile')

    def __str__(self):
        return self.user.__str__()

    def get_absolute_url(self):
        return reverse('profile')

    def get_tyscca_id(self):
        return "{}-{}".format(self.user.id, self.user.password[33:39])

    def pay_fees_for_current_year(self):
        current_year = Year.objects.get_or_create(year=datetime.date.today().year)[0]
        self.fees_payed.add(current_year)
        current_site = get_current_site()
        subject = CURRENT_FEES_PAYED_EMAIL['subject'].format(site_name=current_site.name)
        body = CURRENT_FEES_PAYED_EMAIL['body'].format(site_domain=current_site.domain)
        send_mail(
            ugettext(subject),
            ugettext(body),
            settings.DEFAULT_FROM_EMAIL,
            [self.user.email]
        )

    def pay_fees_for_next_year(self):
        next_year = Year.objects.get_or_create(year=datetime.date.today().year + 1)[0]
        self.fees_payed.add(next_year)
        current_site = get_current_site()
        subject = NEXT_FEES_PAYED_EMAIL['subject'].format(site_name=current_site.name)
        body = NEXT_FEES_PAYED_EMAIL['body'].format(site_domain=current_site.domain)
        send_mail(
            ugettext(subject),
            ugettext(body),
            settings.DEFAULT_FROM_EMAIL,
            [self.user.email]
        )

    def fees_payed_for_current_year(self):
        return self.fees_payed.filter(year=datetime.date.today().year).exists()

    def is_possible_reviewer(self, quiz):
        if self.user not in quiz.authors.all():
            if quiz.topic in self.topics_of_interest.filter(profiletopicsofinterest__is_reviewer=True):
                return True
        return False

    def get_reviewer_points(self):
        return sum([quiz.get_max_score() for quiz in self.user.quiz_reviewed.published()])

    def get_author_points(self):
        return sum([quiz.get_max_score() for quiz in self.user.quiz_authored.published()]) * 3

    def get_courses_points(self):
        return sum([lecture.get_teacher_points() for lecture in self.user.lecture_set.all()])

    def get_tutorships_points(self):
        return sum([tutorship.get_tutor_points() for tutorship in self.user.tutorships_followed_set.all()])

    def get_collaboration_points(self):
        return sum([self.get_reviewer_points(), self.get_author_points(),
                    self.get_courses_points(), self.get_tutorships_points()])


def send_user_created_mail(profile):
    current_site = get_current_site()
    subject = USER_CREATED_EMAIL['subject'].format(
        site_name=current_site.name,
        username=profile.user.username,
    )
    body = USER_CREATED_EMAIL['body'].format(
        site_domain=current_site.domain,
        username=profile.user.username,
        first_name=profile.user.first_name,
        last_name=profile.user.last_name,
        email=profile.user.email,
    )
    send_mail(ugettext(subject), ugettext(body),
              settings.DEFAULT_FROM_EMAIL, [settings.EMAIL_HOST_USER])


@receiver(post_save, sender=Profile)
def notify_user_creation(instance, created, **kwargs):
    if created:
        send_user_created_mail(instance)


class ProfileTopicsOfInterestQuerySet(models.QuerySet):
    def experts(self):
        return self.filter(is_reviewer=True)


@python_2_unicode_compatible
class ProfileTopicsOfInterest(models.Model):
    profile = models.ForeignKey(Profile)
    topic = models.ForeignKey(Topic)
    is_reviewer = models.BooleanField(_('I would like to be part of reviewers team for this topic'),
                                      default=False)
    objects = ProfileTopicsOfInterestQuerySet.as_manager()

    def __str__(self):
        return "{} {}".format(self.profile.user.username, self.topic)


class State(object):
    DRAFT = 'draft'
    PENDING_REVIEWER = 'pending_reviewer'
    PENDING_REVIEW = 'pending_review'
    REVIEWED = 'reviewed'
    PUBLISHED = 'published'
    ARCHIVED = 'archived'

    CHOICES = (
        (DRAFT, _('draft')),
        (PENDING_REVIEWER, _('pending reviewer')),
        (PENDING_REVIEW, _('pending review')),
        (REVIEWED, _('reviewed')),
        (PUBLISHED, _('published')),
        (ARCHIVED, _('archived')),
    )


class QuizQuerySet(models.QuerySet):
    def published(self):
        return self.filter(state=State.PUBLISHED)


@python_2_unicode_compatible
class Quiz(TimeStampedModel):
    title = models.CharField(_('titre'), max_length=255, unique=True)
    topic = models.ForeignKey(Topic, verbose_name=_('topic'))
    level = models.CharField(_('level'), max_length=1, choices=LEVEL_CHOICES)
    authors = models.ManyToManyField(User,
                                     related_name='quiz_authored')
    reviewers = models.ManyToManyField(User,
                                       related_name='quiz_reviewed')
    description = RichTextField(_('description'))
    explanation = RichTextField(
        _('explanation'),
        help_text=_('Explanation will be displayed once the user has taken the quiz.'),
    )
    get_home_message = models.TextField(_('get home message'), blank=True)
    state = FSMField(
        verbose_name=_('publication state'),
        default=State.DRAFT,
        choices=State.CHOICES,
    )
    pub_date = models.DateTimeField(_('publication date'), blank=True, null=True)
    objects = QuizQuerySet.as_manager()

    class Meta:
        ordering = ['-pub_date', 'title']
        verbose_name = _('quiz')
        verbose_name_plural = _('quizzes')
        permissions = (
            ('review_quiz', _('Review quiz')),
        )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('quiz:quiz-detail', kwargs={'pk': self.pk})

    def notify_publication(self):
        current_site = get_current_site()
        subject = QUIZ_PUBLISHED_EMAIL['subject'].format(
            site_name=current_site.name,
            quiz_title=self.title,
        )
        body = QUIZ_PUBLISHED_EMAIL['body'].format(
            site_domain=current_site.domain,
            ref=self.get_absolute_url(),
        )
        email_tuple = ((
            ugettext(subject),
            ugettext(body),
            settings.DEFAULT_FROM_EMAIL,
            [profile.user.email]
        ) for profile in self.topic.profile_set.filter(accept_emails=True))
        send_mass_mail(email_tuple)

    def has_questions(self):
        return self.question_set.all().exists()
    has_questions.hint = _('a quiz must have at least one question')

    def is_new(self):
        return (self.created + datetime.timedelta(weeks=12)) > timezone.now()

    def send_comment_to_author(self, message, reviewer):
        current_site = get_current_site()
        subject = QUIZ_COMMENT_EMAIL['subject'].format(
            site_name=current_site.name,
            quiz_title=self
        )
        body = message + QUIZ_COMMENT_EMAIL['body'].format(
            site_domain=current_site.domain,
        )
        email = EmailMessage(
            subject=subject,
            body=body,
            to=[author.email for author in self.authors.all()],
            headers={'Reply-To': reviewer}
        )
        email.send()

    def weight(self):
        '''
        The weight indicates the sum of all question's ponderation
        '''
        return self.question_set.aggregate(weight=Sum('ponderation'))['weight']

    def get_max_score(self):
        return sum([question.get_max_score() for question in self.question_set.all()])

    ############################################################
    # State Transitions

    @transition(field=state,
                source=[State.DRAFT],
                target=State.PENDING_REVIEWER,
                conditions=[has_questions])
    def ask_reviewer(self):
        pass

    @transition(field=state,
                source=[State.PENDING_REVIEWER],

cytometry/views.py
from __future__ import unicode_literals

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator

from endless_pagination.views import AjaxListView

from .models import Field
from .models import SubField
from .models import Topic


class FieldListView(AjaxListView):
    model = Field

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FieldListView, self).dispatch(*args, **kwargs)


class SubFieldListView(AjaxListView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(SubFieldListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        field = get_object_or_404(Field, slug=self.kwargs['slug'])
        return SubField.objects.filter(field=field)

    def get_context_data(self, **kwargs):
        context = super(SubFieldListView, self).get_context_data(**kwargs)
        field = get_object_or_404(Field, slug=self.kwargs['slug'])
        context['field'] = field
        return context


class TopicListView(AjaxListView):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TopicListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        subfield = get_object_or_404(SubField, slug=self.kwargs['subfieldslug'])
        return Topic.objects.filter(subfield=subfield)

    def get_context_data(self, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)
        subfield = get_object_or_404(SubField, slug=self.kwargs['subfieldslug'])
        context['field'] = subfield.field
        context['subfield'] = subfield
        return context

cytometry/templates/cytometry/field_list.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load url from future %}

{% block head_title %}
    {% trans 'Fields list' %}
{% endblock %}

{% block breadcrumbs %}
    <li class="active">{% trans 'Fields' %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Fields list' %}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        <div class="endless_page_template">
            {% include 'cytometry/field_list_page.html' %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
{% endblock %}

cytometry/templates/cytometry/field_list_page.html
{% load url from future %}
{% load i18n %}
{% load endless %}

{% paginate object_list %}

<div class="list-group">
    {% for field in object_list %}
        <a href="{% url 'cytometry:subfield-list' field.slug %}" class="list-group-item">{{ field.name|capfirst }}</a>
    {% empty %}
        <li class="list-group-item disabled">{% trans "There are no fields yet" %}</li>
    {% endfor %}
</div>

{% include 'paginator.html' %}

cytometry/templates/cytometry/subfield_list.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load url from future %}

{% block head_title %}
    {% trans 'Subfields for' %} {{ field.name|capfirst }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'cytometry:field-list' %}">{% trans 'Fields' %}</a></li>
    <li class="active">{{ field.name|capfirst }}</li>
{% endblock %}
    
{% block page_title %}
    <div class='container page-header'>
        <h1>{% trans 'Subfields for' %} {{ field.name|capfirst }}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        <div class="endless_page_template">
            {% include 'cytometry/subfield_list_page.html' %}
        </div>
        <a href="{% url 'cytometry:field-list' %}" class="btn btn-default" role="button">{% trans 'Back to fields list' %}</a>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
{% endblock %}

cytometry/templates/cytometry/subfield_list_page.html
{% load url from future %}
{% load i18n %}
{% load endless %}

{% paginate object_list %}

<div class="list-group">
    {% for subfield in object_list %}
        <a href="{% url 'cytometry:topic-list' fieldslug=field.slug subfieldslug=subfield.slug %}" class="list-group-item">{{ subfield.name|capfirst }}</a>
    {% empty %}
        <li class="list-group-item disabled">{% trans "There are no subfields yet for" %} {{ field.name|capfirst }}</li>
    {% endfor %}
</div>

{% include 'paginator.html' %}

cytometry/templates/cytometry/topic_list.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load url from future %}

{% block head_title %}
    {% trans 'Topics for' %} {{ subfield.name|capfirst }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'cytometry:field-list' %}">{% trans 'Fields' %}</a></li>
    <li><a href="{% url 'cytometry:subfield-list' slug=field.slug %}">{{ field.name|capfirst }}</a></li>
    <li class="active">{{ subfield.name|capfirst }}</li>
{% endblock %}

{% block page_title %}
    <div class='container page-header'>
        <h1>{% trans 'Topics for' %} {{ subfield.name|capfirst }}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        <div class="endless_page_template">
            {% include 'cytometry/topic_list_page.html' %}
        </div>
        <a href="{% url 'cytometry:subfield-list' slug=field.slug %}" class="btn btn-default" role="button">{% trans 'Back to subfields for' %} {{ field.name|capfirst }}</a>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
{% endblock %}

cytometry/templates/cytometry/topic_list_page.html
{% load url from future %}
{% load i18n %}
{% load endless %}

{% paginate object_list %}

<div class="list-group">
    {% for topic in object_list %}
        <a href="{% url 'quiz:quiz-by-topic-list' fieldslug=field.slug subfieldslug=subfield.slug topicslug=topic.slug %}" class="list-group-item {% if topic.quiz_set.published.count == 0 %}disabled{% endif %}">
            {{ topic.name|capfirst }} ({{ topic.quiz_set.published.count }}  {% trans 'quizzes' %})
        </a>
    {% empty %}
        <li class="list-group-item disabled">{% trans "There are no topics yet for" %} {{ subfield.name|capfirst }}</li>
    {% endfor %}
</div>

{% include 'paginator.html' %}