escca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

from django.contrib import admin
from django.contrib.auth.decorators import login_required

from quiz.views import PPPView
from quiz.views import ProfileView
from quiz.views import ProfileUpdateView
from quiz.views import TopicResultsView
from quiz.views import UserTopicsView
from quiz.views import ContactView

from quiz.views import IndexView

from ckeditor import views

admin.autodiscover()
admin.site.site_header = _('ESCCA administration')
admin.site.site_title = _('ESCCA site admin')

urlpatterns = [
    # Examples:
    # url(r'^$', 'escca.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileView.as_view(), name='profile'),
    url(r'^accounts/profile/topic/(?P<pk>\d+)$', TopicResultsView.as_view(), name='topic_results'),
    url(r'^accounts/profile/edit$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/topics/edit$', UserTopicsView.as_view(), name='topics_edit'),
    url(r'^accounts/profile/ppp$', PPPView.as_view(), name='ppp'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    # We must override those urls in order to make them login_required instead of staff_required
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^cytometry/', include('cytometry.urls', namespace='cytometry')),
    url(r'^directory/', include('directory.urls', namespace='directory')),
    url(r'^sponsors/', include('sponsors.urls', namespace='sponsors')),
    url(r'^lectures/', include('lectures.urls', namespace='lectures')),
    url(r'^tutorships/', include('tutorships.urls', namespace='tutorships')),
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import GeneralStatsView
from .views import StatsBySubFieldView
from .views import StatsByTopicView
from .views import StatsByQuizView
from .views import StatsByQuestionView

from .views import QuizCreateView
from .views import QuizUpdateView

from .views import QuizListView
from .views import QuizUserListView
from .views import QuizReviewListView
from .views import QuizByTopicListView
from .views import QuizDetailView
from .views import QuizTakeView
from .views import QuizResultView

from .views import QuizAskReviewView
from .views import QuizAddReviewerView
from .views import QuizPopReviewerView
from .views import QuizCommentView
from .views import QuizReviewView
from .views import QuizPublishView
from .views import QuizArchiveView

from .views import MailToUsersView

urlpatterns = [
    url(r'^$', QuizListView.as_view(), name='quiz-list'),
    url(r'^stats/$', GeneralStatsView.as_view(), name='quiz-stats'),
    url(r'^stats/by_subfield/(?P<pk>\d+)$', StatsBySubFieldView.as_view(), name='quiz-stats-by-subfield'),
    url(r'^stats/by_topic/(?P<pk>\d+)$', StatsByTopicView.as_view(), name='quiz-stats-by-topic'),
    url(r'^stats/by_quiz/(?P<pk>\d+)$', StatsByQuizView.as_view(), name='quiz-stats-by-quiz'),
    url(r'^stats/by_question/(?P<pk>\d+)$', StatsByQuestionView.as_view(), name='quiz-stats-by-question'),
    url(r'^review/$', QuizReviewListView.as_view(), name='quiz-review-list'),
    url(r'^user/$', QuizUserListView.as_view(), name='quiz-user-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)/(?P<topicslug>[-_\w]+)/$',
        QuizByTopicListView.as_view(), name='quiz-by-topic-list'),
    url(r'^create$', QuizCreateView.as_view(), name='quiz-create'),
    url(r'^(?P<pk>\d+)/$', QuizDetailView.as_view(), name='quiz-detail'),
    url(r'^(?P<pk>\d+)/update$', QuizUpdateView.as_view(), name='quiz-update'),
    url(r'^(?P<pk>\d+)/ask_review$', QuizAskReviewView.as_view(), name='quiz-ask-review'),
    url(r'^(?P<pk>\d+)/add-reviewer$', QuizAddReviewerView.as_view(), name='quiz-add-reviewer'),
    url(r'^(?P<pk>\d+)/pop-reviewer$', QuizPopReviewerView.as_view(), name='quiz-pop-reviewer'),
    url(r'^(?P<pk>\d+)/comment$', QuizCommentView.as_view(), name='quiz-comment'),
    url(r'^(?P<pk>\d+)/review$', QuizReviewView.as_view(), name='quiz-review'),
    url(r'^(?P<pk>\d+)/publish$', QuizPublishView.as_view(), name='quiz-publish'),
    url(r'^(?P<pk>\d+)/archive$', QuizArchiveView.as_view(), name='quiz-archive'),
    url(r'^(?P<pk>\d+)/take$', QuizTakeView.as_view(), name='quiz-take'),
    url(r'^(?P<pk>\d+)/result$', QuizResultView.as_view(), name='quiz-result'),
    url(r'^mail_to_users/$', MailToUsersView.as_view(), name='mail_to_users'),
]

tutorships/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import TutorshipCreateView
from .views import TutorshipDetailView
from .views import TutorshipDeleteView
from .views import TutorshipListView
from .views import TutorshipManageListView
from .views import TutorshipUpdateView
from .views import TutorshipAcceptView
from .views import TutorshipCancelView

from .views import StepCreateView
from .views import StepDeleteView
from .views import StepUpdateView

from .views import EvaluationCreateView


urlpatterns = [
    url(r'^$', TutorshipListView.as_view(), name='tutorship-list'),
    url(r'^committee_panel/$', TutorshipManageListView.as_view(), name='tutorship-committee-list'),
    url(r'^ask$', TutorshipCreateView.as_view(), name='tutorship-create'),
    url(r'^(?P<pk>\d+)/$', TutorshipDetailView.as_view(), name='tutorship-detail'),
    url(r'^(?P<pk>\d+)/delete/$', TutorshipDeleteView.as_view(), name='tutorship-delete'),
    url(r'^(?P<pk>\d+)/update/$', TutorshipUpdateView.as_view(), name='tutorship-update'),
    url(r'^(?P<pk>\d+)/accept/$', TutorshipAcceptView.as_view(), name='tutorship-accept'),
    url(r'^(?P<pk>\d+)/cancel/$', TutorshipCancelView.as_view(), name='tutorship-cancel'),
    url(r'^(?P<tutorship>\d+)/steps/create/$', StepCreateView.as_view(), name='step-create'),
    url(r'^(?P<tutorship>\d+)/steps/(?P<pk>\d+)/delete/$', StepDeleteView.as_view(), name='step-delete'),
    url(r'^(?P<tutorship>\d+)/steps/(?P<pk>\d+)/update/$', StepUpdateView.as_view(), name='step-update'),
    url(r'^(?P<tutorship>\d+)/steps/(?P<step>\d+)/evaluation/create/$',
        EvaluationCreateView.as_view(), name='evaluation-create'),
]

tutorships/models.py
from __future__ import unicode_literals

import datetime

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from ckeditor.fields import RichTextField

from guardian.shortcuts import assign_perm
from guardian.shortcuts import remove_perm

from cytometry.models import Topic

from .emails import send_tutorship_accepted
from .emails import confirm_tutorship_accepted
from .emails import send_tutorship_canceled


@python_2_unicode_compatible
class Tutorship(models.Model):
    title = models.CharField(_('title'), max_length=255)
    topic = models.ForeignKey(Topic, verbose_name=_('topic'))
    start = models.DateField(_('start date of the tutoring'), blank=True, null=True)
    description = RichTextField(_('description'))
    tutoree = models.ForeignKey(User, verbose_name=_('tutoree'), blank=True, null=True)
    tutor = models.ForeignKey(
        User,
        verbose_name=_('tutor'),
        blank=True,
        null=True,
        related_name='tutorships_followed_set',
    )

    class Meta:
        verbose_name = _('tutoring')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tutorships:tutorship-detail', kwargs={'pk': self.pk})

    def remove_tutor(self):
        send_tutorship_canceled(self.tutoree, self.tutor, self)
        for step in self.step_set.all():
            try:
                step.evaluation.delete()
            except:
                pass
            else:
                step.evaluation_request_sent = False
                step.save()
        remove_perm('change_tutorship', self.tutor, self)

    def inform_tutorship_accepted(self):
        send_tutorship_accepted(self.tutoree, self.tutor, self)
        confirm_tutorship_accepted(self.tutoree, self.tutor, self)

    def has_late_evaluation(self):
        if self.step_set.deadline_passed().exists():
            try:
                self.step_set.last().evaluation
            except:
                if (self.step_set.last().get_deadline().date() + datetime.timedelta(weeks=4)) < datetime.date.today():
                    return True
        return False

    def get_tutor_points(self):
        return sum([step.get_tutor_points() for step in self.step_set.all()])


@receiver(post_save, sender=Tutorship)
def assign_tutorship_perms(instance, created, **kwargs):
    if created:
        assign_perm('change_tutorship', instance.tutoree, instance)
        assign_perm('delete_tutorship', instance.tutoree, instance)
    if instance.tutor:
        assign_perm('change_tutorship', instance.tutor, instance)


class StepQuerySet(models.QuerySet):
    def deadline_passed(self):
        today = datetime.date.today()
        queryset = self.exclude(tutorship__start=None).filter(evaluation_request_sent=False)
        excluded = []
        for step in queryset:
            if step.get_deadline().date() > today:
                excluded.append(step.id)
        return queryset.exclude(id__in=excluded)


@python_2_unicode_compatible
class Step(models.Model):
    title = models.CharField(_('title'), max_length=255)
    description = RichTextField(_('description'))
    duration = models.PositiveIntegerField(_('duration'))
    tutorship = models.ForeignKey(Tutorship, verbose_name=_('tutoring'))
    evaluation_request_sent = models.BooleanField(default=False)
    objects = StepQuerySet.as_manager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('tutorships:tutorship-detail', kwargs={'pk': self.tutorship.pk})

    def get_deadline(self):
        """
        Adds the start of the tutoring and all the durations of steps before this one,
        including this one
        Return it in a datetime object
        """
        return datetime.datetime.combine(
            self.tutorship.start + datetime.timedelta(
                weeks=sum([step.duration for step in self.tutorship.step_set.filter(pk__lte=self.pk)])
            ),
            datetime.datetime.min.time()
        )

    def get_tutor_points(self):
        if datetime.date.today() > self.get_deadline().date() and hasattr(self, 'evaluation'):
            return self.evaluation.satisfaction * self.duration / 100
        else:
            return 0


def validate_percentage(value):
    if not 0 <= value <= 100:
        raise ValidationError("satisfaction must be a percentage")


@python_2_unicode_compatible
class Evaluation(models.Model):
    satisfaction = models.PositiveIntegerField(_('satisfaction'), validators=[validate_percentage])
    comment = models.TextField(_('comment'))
    step = models.OneToOneField(Step, verbose_name=_('step'))

    def __str__(self):
        return "Evaluation - {}".format(self.step)

    def get_absolute_url(self):
        return reverse('tutorships:tutorship-detail', kwargs={'pk': self.step.tutorship.pk})

tutorships/views.py
from __future__ import unicode_literals

import datetime

from django.core.urlresolvers import reverse_lazy
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from braces.views import LoginRequiredMixin
from braces.views import UserPassesTestMixin

from guardian.mixins import PermissionRequiredMixin

from .models import Tutorship
from .models import Step
from .models import Evaluation
from .forms import TutorshipForm
from .forms import TutorshipAcceptForm
from .forms import TutorshipCancelForm
from .forms import StepForm
from .forms import EvaluationForm


class TutorshipListView(LoginRequiredMixin, ListView):
    model = Tutorship

    def get_queryset(self):
        return Tutorship.objects.filter(tutor=None).exclude(tutoree=self.request.user)


class TutorshipManageListView(LoginRequiredMixin, ListView):
    model = Tutorship
    template_name_suffix = '_committee_list'


class TutorshipCreateView(UserPassesTestMixin, CreateView):
    model = Tutorship
    form_class = TutorshipForm
    raise_exception = True

    def test_func(self, user):
        try:
            user.profile
        except AttributeError:
            return False
        return user.profile.fees_payed_for_current_year()

    def form_valid(self, form):
        form.instance.tutoree = self.request.user
        response = super(TutorshipCreateView, self).form_valid(form)
        return response


class TutorshipDetailView(LoginRequiredMixin, DetailView):
    model = Tutorship

    def get_context_data(self, **kwargs):
        context = super(TutorshipDetailView, self).get_context_data(**kwargs)
        context['today'] = datetime.date.today()
        return context


class TutorshipDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'tutorships.delete_tutorship'
    return_403 = True
    model = Tutorship
    success_url = reverse_lazy('tutorships:tutorship-list')


class TutorshipUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'tutorships.change_tutorship'
    return_403 = True
    model = Tutorship
    form_class = TutorshipForm
    template_name_suffix = '_update_form'


class TutorshipAcceptView(LoginRequiredMixin, UpdateView):
    model = Tutorship
    form_class = TutorshipAcceptForm
    template_name_suffix = '_accept_form'

    def form_valid(self, form):
        form.instance.tutor = self.request.user
        form.instance.start = datetime.date.today()
        form.instance.inform_tutorship_accepted()
        return super(TutorshipAcceptView, self).form_valid(form)


class TutorshipCancelView(PermissionRequiredMixin, UpdateView):
    permission_required = 'tutorships.change_tutorship'
    return_403 = True
    model = Tutorship
    form_class = TutorshipCancelForm
    template_name_suffix = '_cancel_form'

    def form_valid(self, form):
        form.instance.remove_tutor()
        form.instance.tutor = None
        form.instance.start = None
        return super(TutorshipCancelView, self).form_valid(form)


class StepCreateView(LoginRequiredMixin, CreateView):
    model = Step
    form_class = StepForm

    def form_valid(self, form):
        form.instance.tutorship = self.get_context_data()['tutorship']
        return super(StepCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(StepCreateView, self).get_context_data(**kwargs)
        context['tutorship'] = get_object_or_404(Tutorship, pk=self.kwargs['tutorship'])
        return context


class StepDeleteView(LoginRequiredMixin, DeleteView):
    model = Step

    def get_success_url(self):
        return reverse('tutorships:tutorship-detail', kwargs={'pk': self.object.tutorship.pk})


class StepUpdateView(LoginRequiredMixin, UpdateView):
    model = Step
    form_class = StepForm
    template_name_suffix = '_update_form'


class EvaluationCreateView(LoginRequiredMixin, CreateView):
    model = Evaluation
    form_class = EvaluationForm

    def form_valid(self, form):
        form.instance.step = self.get_context_data()['step']
        return super(EvaluationCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EvaluationCreateView, self).get_context_data(**kwargs)
        context['step'] = get_object_or_404(Step, pk=self.kwargs['step'])
        context['tutorship'] = get_object_or_404(Tutorship, pk=self.kwargs['tutorship'])
        return context

tutorships/templates/tutorships/evaluation_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Evaluate your work relation with your tutor' %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li><a href="{% url 'tutorships:tutorship-detail' pk=tutorship.pk %}">{{ tutorship }}</a></li>
    <li><a href="{% url 'tutorships:tutorship-detail' pk=tutorship.pk %}">{{ step }}</a></li>
    <li class="active">{% trans 'Evaluate' %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Evaluate your work relation with your tutor' %}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        {% crispy form %}
    </div>
{% endblock %}

tutorships/templates/tutorships/step_confirm_delete.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load guardian_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Delete' %} {{ object }} ?
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li><a href="{% url 'tutorships:tutorship-detail' pk=object.tutorship.pk %}">{{ object.tutorship }}</a></li>
    <li class="active">{% trans "Delete" %} {{ object }}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans "Delete step" %} {{ object }}</h1>
    </div>
{% endblock %}

{% block content %}
    <br>
    <div class='container'>
        <div class='row'>
            <form action="" method="post">{% csrf_token %}
                <p>{% trans "Are you sure you want to delete the step" %} "{{ object }}" ?</p>
                <input class="btn btn-primary" type="submit" value="{% trans "Yes, I'm sure" %}" />
                <a href="{% url 'tutorships:tutorship-detail' pk=object.tutorship.pk %}" class="btn btn-default" role="button">{% trans 'No, take me back to the tutoring' %}</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

tutorships/templates/tutorships/step_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Add a step to the Tutoring' %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li><a href="{% url 'tutorships:tutorship-detail' pk=tutorship.pk %}">{% trans "Tutorings" %}</a></li>
    <li class="active">{% trans 'Add a step to the tutoring' %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Add a step to the tutoring' %}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        {% crispy form %}
    </div>
{% endblock %}

tutorships/templates/tutorships/step_update_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans "Edit" %} {{ object }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li><a href="{% url 'tutorships:tutorship-detail' pk=object.tutorship.pk %}">{{ object.tutorship }}</a></li>
    <li class="active">{% trans "Edit" %} {{ object }}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans "Edit" %} {{ object }}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        {% crispy form %}
    </div>
{% endblock %}

tutorships/templates/tutorships/tutorship_detail.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load guardian_tags %}
{% load humanize %}
{% load url from future %}

{% block head_title %}
    {{ object }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li class="active">{{ object }}</li>
{% endblock %}

{% block page_title %}
    {% get_obj_perms request.user for object as 'object_perms' %}
    <div class="container page-header">
        <h1>
            {{ object }}
            {% if "change_tutorship" in object_perms %}
                <a href="{% url 'tutorships:tutorship-update' object.pk %}" class="btn btn-default" role="button"><span class="fa fa-edit"></span> {% trans 'Edit' %}</a>
            {% else %}
                <a href="{% url 'tutorships:tutorship-accept' object.pk %}" class="btn btn-success btn-lg" role="button"><span class="fa fa-check"></span> {% trans 'Supervise this tutoring' %}</a>
            {% endif %}
            {% if user == object.tutor %}
                <a href="{% url 'tutorships:tutorship-cancel' object.pk %}" class="btn btn-warning" role="button"><span class="fa fa-cross"></span> {% trans 'Cancel my supervision for this tutoring' %}</a>
            {% endif %}
            {% if "delete_tutorship" in object_perms %}
                <a href="{% url 'tutorships:tutorship-delete' object.pk %}" class="btn btn-danger" role="button"><span class="fa fa-close"></span> {% trans 'Delete' %}</a>
            {% endif %}
        </h1>
    </div>
{% endblock %}

{% block content %}
    {% get_obj_perms request.user for object as 'object_perms' %}
    <div class='container'>
        <p><strong>{% trans "Tutoree : " %}</strong>{{ tutorship.tutoree.first_name|title }} {{ tutorship.tutoree.last_name|title }}</p>
        {% if tutorship.tutor %}
            <p><strong>{% trans "Tutor : " %}</strong>{{ tutorship.tutor.first_name|title }} {{ tutorship.tutor.last_name|title }}</p>
        {% endif %}
        {{ object.description|safe }}
        <h3>
            {% trans 'Steps' %} : 
            {% if "change_tutorship" in object_perms %}
                <a href="{% url 'tutorships:step-create' tutorship=tutorship.pk %}" class="btn btn-default" role="button"><span class="fa fa-plus"></span> {% trans 'Add a step to the tutoring' %}</a>
            {% endif %}
        </h3>
        <ul class="list-group">
            {% for step in object.step_set.all %}
                <li class="list-group-item">
                    <h3 class="list-group-item-heading">
                        {{ step }}
                        {% if step.tutorship.start and today > step.get_deadline.date and user == step.tutorship.tutoree and step.evaluation == None %}
                            <a href="{% url 'tutorships:evaluation-create' tutorship=tutorship.pk step=step.pk %}" class="btn btn-success" role="button"><span class="fa fa-edit"></span> {% trans 'Evaluate this step' %}</a>
                        {% endif %}
                    </h3>
                    <p><strong>{% trans "Duration" %} : </strong> {{ step.duration }} {% trans "weeks" %}</p>
                    {% if step.tutorship.start %}
                        <p><strong>{% trans "Deadline for this step" %} : </strong> {{ step.get_deadline|naturalday }}</p>
                        {% if today < step.get_deadline.date %}
                            <p><strong>{% trans "Remaining time" %} : </strong> {{ step.get_deadline|naturaltime }}</p>
                        {% endif %}
                    {% endif %}
                    {{ step.description|safe }}
                    {% if perms.tutorships.change_tutorship and step.evaluation %}
                        <div class="panel panel-default">
                            <div class="panel-heading">{% trans "Evaluation" %}</div>
                            <div class="panel-body">
                                <p><strong>{% trans "Satisfaction of the tutoree : " %}</strong>{{ step.evaluation.satisfaction }} %</p>
                                <p><strong>{% trans "Comments :" %}</strong></p>
                                {{ step.evaluation.comment|linebreaks }}
                            </div>
                        </div>
                    {% endif %}
                    {% if "change_tutorship" in object_perms %}
                        <a href="{% url 'tutorships:step-update' tutorship=step.tutorship.pk pk=step.pk %}" class="btn btn-default btn-xs" role="button">
                            <span class="fa fa-edit"></span> {% trans 'Edit' %}
                        </a>
                        <a href="{% url 'tutorships:step-delete' tutorship=step.tutorship.pk pk=step.pk %}" class="btn btn-danger btn-xs" role="button">
                            <span class="fa fa-close"></span> {% trans 'Remove this step from tutoring' %}
                        </a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

tutorships/templates/tutorships/tutorship_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Request a Tutoring' %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans "Tutorings" %}</a></li>
    <li class="active">{% trans 'Request' %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Request a tutoring' %}</h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        {% crispy form %}
    </div>
{% endblock %}

tutorships/templates/tutorships/tutorship_list.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load url from future %}

{% block head_title %}
    {% trans 'Tutorings' %}
{% endblock %}

{% block breadcrumbs %}
    <li class="active">{% trans 'Tutorings' %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans "Tutorings" %}</h1>
    </div>
{% endblock %}

{% block content %}
    <br>
    <div class='container'>
    <h2>{% trans "Tutorings that need supervising" %}</h2>
        <div class="list-group">
            {% for tutorship in object_list %}
                {% include 'tutorships/tutorship_list_item.html' %}
            {% empty %}
                <li class="list-group-item disabled">{% trans "There are no tutorings in need of supervising yet" %}</li>
            {% endfor %}
        </div>
    </div>
    <div class='container'>
    <h2>{% trans "Your Tutorings" %}</h2>
        <div class="list-group">
            {% for tutorship in user.tutorship_set.all %}
                {% include 'tutorships/tutorship_list_item.html' %}
            {% empty %}
                <li class="list-group-item disabled">{% trans "You are not in a process of tutoring yet" %}</li>
            {% endfor %}
        </div>
        <a href="{% url 'tutorships:tutorship-create' %}" class="btn btn-primary" role="button"><span class="fa fa-plus"></span> {% trans 'Request a tutoring' %}</a>
    </div>
    <div class='container'>
    <h2>{% trans "Tutorings you are supervising" %}</h2>
        <div class="list-group">
            {% for tutorship in user.tutorships_followed_set.all %}
                {% include 'tutorships/tutorship_list_item.html' %}
            {% empty %}
                <li class="list-group-item disabled">{% trans "You are not supervising any tutoring yet" %}</li>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}