cytometry/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import FieldListView
from .views import SubFieldListView
from .views import TopicListView

urlpatterns = [
    url(r'^$', FieldListView.as_view(), name='field-list'),
    url(r'^(?P<slug>[-_\w]+)/$', SubFieldListView.as_view(), name='subfield-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)$', TopicListView.as_view(), name='topic-list'),
]

escca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

from django.contrib import admin
from django.contrib.auth.decorators import login_required

from quiz.views import PPPView
from quiz.views import ProfileView
from quiz.views import ProfileUpdateView
from quiz.views import TopicResultsView
from quiz.views import UserTopicsView
from quiz.views import ContactView

from quiz.views import IndexView

from ckeditor import views

admin.autodiscover()
admin.site.site_header = _('ESCCA administration')
admin.site.site_title = _('ESCCA site admin')

urlpatterns = [
    # Examples:
    # url(r'^$', 'escca.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileView.as_view(), name='profile'),
    url(r'^accounts/profile/topic/(?P<pk>\d+)$', TopicResultsView.as_view(), name='topic_results'),
    url(r'^accounts/profile/edit$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/topics/edit$', UserTopicsView.as_view(), name='topics_edit'),
    url(r'^accounts/profile/ppp$', PPPView.as_view(), name='ppp'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    # We must override those urls in order to make them login_required instead of staff_required
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^cytometry/', include('cytometry.urls', namespace='cytometry')),
    url(r'^directory/', include('directory.urls', namespace='directory')),
    url(r'^sponsors/', include('sponsors.urls', namespace='sponsors')),
    url(r'^lectures/', include('lectures.urls', namespace='lectures')),
    url(r'^tutorships/', include('tutorships.urls', namespace='tutorships')),
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import GeneralStatsView
from .views import StatsBySubFieldView
from .views import StatsByTopicView
from .views import StatsByQuizView
from .views import StatsByQuestionView

from .views import QuizCreateView
from .views import QuizUpdateView

from .views import QuizListView
from .views import QuizUserListView
from .views import QuizReviewListView
from .views import QuizByTopicListView
from .views import QuizDetailView
from .views import QuizTakeView
from .views import QuizResultView

from .views import QuizAskReviewView
from .views import QuizAddReviewerView
from .views import QuizPopReviewerView
from .views import QuizCommentView
from .views import QuizReviewView
from .views import QuizPublishView
from .views import QuizArchiveView

from .views import MailToUsersView

urlpatterns = [
    url(r'^$', QuizListView.as_view(), name='quiz-list'),
    url(r'^stats/$', GeneralStatsView.as_view(), name='quiz-stats'),
    url(r'^stats/by_subfield/(?P<pk>\d+)$', StatsBySubFieldView.as_view(), name='quiz-stats-by-subfield'),
    url(r'^stats/by_topic/(?P<pk>\d+)$', StatsByTopicView.as_view(), name='quiz-stats-by-topic'),
    url(r'^stats/by_quiz/(?P<pk>\d+)$', StatsByQuizView.as_view(), name='quiz-stats-by-quiz'),
    url(r'^stats/by_question/(?P<pk>\d+)$', StatsByQuestionView.as_view(), name='quiz-stats-by-question'),
    url(r'^review/$', QuizReviewListView.as_view(), name='quiz-review-list'),
    url(r'^user/$', QuizUserListView.as_view(), name='quiz-user-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)/(?P<topicslug>[-_\w]+)/$',
        QuizByTopicListView.as_view(), name='quiz-by-topic-list'),
    url(r'^create$', QuizCreateView.as_view(), name='quiz-create'),
    url(r'^(?P<pk>\d+)/$', QuizDetailView.as_view(), name='quiz-detail'),
    url(r'^(?P<pk>\d+)/update$', QuizUpdateView.as_view(), name='quiz-update'),
    url(r'^(?P<pk>\d+)/ask_review$', QuizAskReviewView.as_view(), name='quiz-ask-review'),
    url(r'^(?P<pk>\d+)/add-reviewer$', QuizAddReviewerView.as_view(), name='quiz-add-reviewer'),
    url(r'^(?P<pk>\d+)/pop-reviewer$', QuizPopReviewerView.as_view(), name='quiz-pop-reviewer'),
    url(r'^(?P<pk>\d+)/comment$', QuizCommentView.as_view(), name='quiz-comment'),
    url(r'^(?P<pk>\d+)/review$', QuizReviewView.as_view(), name='quiz-review'),
    url(r'^(?P<pk>\d+)/publish$', QuizPublishView.as_view(), name='quiz-publish'),
    url(r'^(?P<pk>\d+)/archive$', QuizArchiveView.as_view(), name='quiz-archive'),
    url(r'^(?P<pk>\d+)/take$', QuizTakeView.as_view(), name='quiz-take'),
    url(r'^(?P<pk>\d+)/result$', QuizResultView.as_view(), name='quiz-result'),
    url(r'^mail_to_users/$', MailToUsersView.as_view(), name='mail_to_users'),
]

quiz/views.py
from __future__ import unicode_literals

import datetime

from django.conf import settings

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse

from django.forms.formsets import formset_factory

from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from django.utils.decorators import method_decorator
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext_lazy as _

from django.views.generic import View
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.list import ListView

# from django_fsm import TransitionNotAllowed
from braces.views import SuperuserRequiredMixin

from endless_pagination.views import AjaxListView

from easy_pdf.views import PDFTemplateView

from extra_views import CreateWithInlinesView
from extra_views import UpdateWithInlinesView

from guardian.mixins import PermissionRequiredMixin

from cytometry.models import Topic
from cytometry.models import SubField
from cytometry.models import Field

from sponsors.models import Sponsor

from .forms import AnswerForm
from .forms import ContactForm
from .forms import ProfileForm
from .forms import QuizForm
from .forms import QuestionInline
from .forms import TopicInline
from .forms import UserTopicsForm
from .forms import QuizCommentForm

from .models import Answer
from .models import Profile
from .models import Quiz
from .models import Sitting
from .models import State


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['sponsors'] = Sponsor.objects.displayable()
        if context['sponsors'].count() > 0:
            context['sponsor_columns'] = 12 / context['sponsors'].count()
        return context


class ProfileView(ListView):
    model = Topic
    template_name = 'profile.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = Topic.objects.filter(quiz__sitting__user=self.request.user).distinct()
        for topic in queryset:
            best_sittings = self.request.user.sitting_set.filter(quiz__topic=topic).only_best_scores()
            topic.right = best_sittings.overall_right()
            topic.wrong = best_sittings.overall_wrong()
            topic.unknown = best_sittings.overall_unknown()
            topic.score = best_sittings.overall_score()
            topic.right_percentage = best_sittings.overall_right_percentage()
            topic.wrong_percentage = best_sittings.overall_wrong_percentage()
            topic.unknown_percentage = best_sittings.overall_unknown_percentage()
        return queryset


class PPPView(PDFTemplateView):
    template_name = 'ppp.html'

    def get_context_data(self, **kwargs):
        context = super(PPPView, self).get_context_data(**kwargs)
        context['today'] = datetime.date.today()
        return context


class TopicResultsView(ListView):
    model = Sitting
    template_name = 'quiz/topic_results.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TopicResultsView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return self.request.user.sitting_set.filter(quiz__topic=self.kwargs['pk']).only_best_scores()


class ContactView(SuccessMessageMixin, FormView):
    template_name = 'quiz/contact_form.html'
    form_class = ContactForm
    success_url = '/'
    success_message = _('Your message has been successfully sent')

    def form_valid(self, form):
        form.send_email(self.request.POST['email'],
                        self.request.POST['subject'],
                        self.request.POST['message'])
        return super(ContactView, self).form_valid(form)


class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileUpdateView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user.profile


class UserTopicsView(UpdateWithInlinesView):
    model = Profile
    inlines = [TopicInline]
    form_class = UserTopicsForm
    template_name_suffix = '_topics_update_form'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(UserTopicsView, self).dispatch(*args, **kwargs)

    def get_object(self, queryset=None):
        return self.request.user.profile


class QuizCreateView(CreateWithInlinesView):
    model = Quiz
    inlines = [QuestionInline]
    form_class = QuizForm
    template_name_suffix = '_create_form'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuizCreateView, self).dispatch(*args, **kwargs)

    def forms_valid(self, form, inlines):
        response = super(QuizCreateView, self).forms_valid(form, inlines)
        form.instance.authors.add(self.request.user)
        return response


class QuizUpdateView(PermissionRequiredMixin, UpdateWithInlinesView):
    permission_required = 'quiz.change_quiz'
    return_403 = True
    model = Quiz
    inlines = [QuestionInline]
    form_class = QuizForm
    template_name_suffix = '_update_form'


class QuizAskReviewView(PermissionRequiredMixin, SingleObjectMixin, View):
    permission_required = 'quiz.change_quiz'
    return_403 = True
    model = Quiz

    def get(self, request, *args, **kwargs):
        quiz = self.get_object()
        quiz.ask_reviewer()
        quiz.save()
        return redirect(quiz)


class QuizAddReviewerView(SingleObjectMixin, View):
    model = Quiz

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuizAddReviewerView, self).dispatch(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        quiz = self.get_object()
        if self.request.user.profile.is_possible_reviewer(quiz):
            quiz.add_reviewer(self.request.user)
            quiz.save()
        else:
            raise PermissionDenied
        return redirect(quiz)


class QuizPopReviewerView(PermissionRequiredMixin, SingleObjectMixin, View):
    permission_required = 'quiz.review_quiz'
    return_403 = True
    model = Quiz

    def post(self, request, *args, **kwargs):
        quiz = self.get_object()
        quiz.pop_reviewer(self.request.user)
        quiz.save()
        return redirect(quiz)


class QuizCommentView(PermissionRequiredMixin, SuccessMessageMixin, SingleObjectMixin, FormView):
    permission_required = 'quiz.review_quiz'
    return_403 = True
    model = Quiz
    template_name = 'quiz/quiz_comment_form.html'
    form_class = QuizCommentForm
    success_message = _('Your comment has been successfully sent to the author')

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(QuizCommentView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(QuizCommentView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object.send_comment_to_author(self.request.POST['message'], self.request.user.email)
        return super(QuizCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('quiz:quiz-detail', kwargs={'pk': self.object.pk})


class QuizReviewView(PermissionRequiredMixin, SingleObjectMixin, View):
    permission_required = 'quiz.review_quiz'
    return_403 = True
    model = Quiz

    def get(self, request, *args, **kwargs):
        quiz = self.get_object()
        quiz.review()
        quiz.save()
        return redirect(quiz)


class QuizPublishView(PermissionRequiredMixin, SingleObjectMixin, View):
    permission_required = 'quiz.change_quiz'
    return_403 = True
    model = Quiz

    def get(self, request, *args, **kwargs):
        quiz = self.get_object()
        quiz.publish()
        quiz.save()
        return redirect(quiz)


class QuizArchiveView(PermissionRequiredMixin, SingleObjectMixin, View):
    permission_required = 'quiz.change_quiz'
    return_403 = True
    model = Quiz

    def get(self, request, *args, **kwargs):
        quiz = self.get_object()
        quiz.archive()
        quiz.save()
        return redirect(quiz)


class QuizListView(AjaxListView):
    model = Quiz

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuizListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Quiz.objects.filter(topic__in=self.request.user.profile.topics_of_interest.all()).published()


class QuizUserListView(AjaxListView):
    model = Quiz
    template_name_suffix = '_user_list'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuizUserListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return self.request.user.quiz_authored.all()


class QuizReviewListView(AjaxListView):
    model = Quiz
    template_name_suffix = '_review_list'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(QuizReviewListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        return Quiz.objects.filter(
            topic__in=self.request.user.profile.topics_of_interest.filter(
                profiletopicsofinterest__is_reviewer=True
            ),

quiz/templates/quiz/profile_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Profile Update' %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'profile' %}">{% trans "Profile" %}</a></li>
    <li class="active">{% trans "Profile Edition" %}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Profile Update' %}</h1>
    </div>
{% endblock %}

{% block content %}
    <br>
    <div class="container">
        {% crispy form %}
    </div>
{% endblock %}

quiz/templates/quiz/quiz_comment_form.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load crispy_forms_tags %}
{% load url from future %}

{% block head_title %}
    {% trans 'Comment for quiz' %} {{object}}
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>{% trans 'Send a comment for quiz' %} {{ object }}</h1>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'quiz:quiz-review-list' %}">{% trans 'Help Reviewing Quizzes' %}</a></li>
    <li><a href="{% url 'quiz:quiz-detail' object.pk %}">{{ object }}</a></li>
    <li class="active">{% trans 'Comment' %}</li>
{% endblock %}

{% block content %}
    <br>
    <div class="container">
        {% crispy form %}
    </div>
{% endblock %}

quiz/templates/quiz/quiz_create_form.html
{% extends "quiz/quiz_form.html" %}

{% load i18n %}

{% block head_title %}
    {% trans 'Create a new Quiz' %}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'quiz:quiz-user-list' %}">{% trans 'Quiz Submission' %}</a></li>
    <li class="active">{% trans 'Create a Quiz' %}</li>
{% endblock %}

{% block page_title %}
    <div class='container page-header'>
        <h1>{% trans 'Create a new Quiz' %}</h1>
    </div>
{% endblock %}

quiz/templates/quiz/quiz_detail.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load guardian_tags %}
{% load url from future %}

{% block head_title %}
    {{ object.title|capfirst }}
{% endblock %}

{% block breadcrumbs %}
    {% get_obj_perms request.user for object as 'object_perms' %}
    {% if 'change_quiz' in object_perms %}
        <li><a href="{% url 'quiz:quiz-user-list' %}">{% trans 'Quiz Submission' %}</a></li>
    {% elif 'review_quiz' in object_perms or quiz.state == 'pending_reviewer' and possible_reviewer %}
        <li><a href="{% url 'quiz:quiz-review-list' %}">{% trans 'Help Reviewing Quizzes' %}</a></li>
    {% else %}
        {% if object.topic in request.user.profile.topics_of_interest.all %}
            <li><a href="{% url 'quiz:quiz-list' %}">{% trans 'Dashboard' %}</a></li>
        {% else %}
            <li><a href="{% url 'cytometry:field-list' %}">{% trans 'Fields' %}</a></li>
            <li><a href="{% url 'cytometry:subfield-list' slug=object.topic.subfield.field.slug %}">{{ object.topic.subfield.field|capfirst }}</a></li>
            <li><a href="{% url 'cytometry:topic-list' fieldslug=object.topic.subfield.field.slug subfieldslug=object.topic.subfield.slug %}">{{ object.topic.subfield|capfirst }}</a></li>
            <li><a href="{% url 'quiz:quiz-by-topic-list' fieldslug=object.topic.subfield.field.slug subfieldslug=object.topic.subfield.slug topicslug=object.topic.slug %}">{{ object.topic|capfirst }}</a></li>
        {% endif %}
    {% endif %}
    <li class="active">{{ object }}</li>
{% endblock %}

{% block page_title %}
    <div class='container page-header'>
        <h1>{{ object|capfirst }} <small><span class="label label-default">{{ object.topic }}</span></small></h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        {% get_obj_perms request.user for object as 'object_perms' %}
        <div class="row">
            <div class="col-sm-8">
                {{ object.description|safe }}
                {% if 'change_quiz' in object_perms or 'review_quiz' in object_perms %}
                    <h2>{% trans 'Questions :' %}</h2>
                    <ul class="list-group">
                        {% for question in object.question_set.all %}
                            <li class="list-group-item">
                                <h4 class="list-group-item-heading">{{ question }}</h4>
                                <br>
                                <p class="list-group-item-text">
                                    <strong>{% trans "Answer" %} : </strong>
                                    {% if question.correct %}
                                        <span class="label label-success">{{ question.correct }}</span>
                                    {% else %}
                                        <span class="label label-danger">{{ question.correct }}</span>
                                    {% endif %}
                                </p>
                                <br>
                                <p class="list-group-item-text"><strong>{% trans "Explanation" %} : </strong>{{ question.explanation }}</p>
                                <p class="list-group-item-text"><strong>{% trans "Ponderation" %} : </strong>{{ question.ponderation }}</p>
                            </li>
                        {% endfor %}
                    </ul>
                    {% include 'quiz/quiz_explanation.html' with explanation=object.explanation %}
                    {% include 'quiz/quiz_get_home_message.html' with get_home_message=object.get_home_message %}
                {% endif %}
            </div>
            <div class="col-sm-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                            {% if 'change_quiz' in object_perms %}
                                <p>
                                    <a href="{% url 'quiz:quiz-update' object.pk %}" class="btn btn-info" role="button"><span class="fa fa-edit"></span> {% trans 'Edit' %}</a>
                                    {% if quiz.state == 'draft' %}
                                        <a href="{% url 'quiz:quiz-ask-review' object.pk %}" class="btn btn-warning" role="button"><span class="fa fa-users"></span> {% trans 'Ask for Reviewers' %}</a>
                                    {% elif quiz.state == 'reviewed' or quiz.state == 'archived' %}
                                        <a href="{% url 'quiz:quiz-publish' object.pk %}" class="btn btn-success" role="button"><span class="fa fa-newspaper-o"></span> {% trans 'Publish' %}</a>
                                    {% elif quiz.state == 'published' %}
                                        <a href="{% url 'quiz:quiz-archive' object.pk %}" class="btn btn-danger" role="button"><span class="fa fa-archive"></span> {% trans 'Archive' %}</a>
                                    {% endif %}
                                </p>
                            {% endif %}
                            {% if quiz.state == 'pending_reviewer' and possible_reviewer %}
                                <p>
                                    <form action="{% url 'quiz:quiz-add-reviewer' object.pk %}" method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-warning" type="submit" value="{% trans 'I want to review this Quiz' %}">
                                    </form>
                                </p>
                            {% endif %}
                            {% if quiz.state == 'pending_review' and 'review_quiz' in object_perms %}
                                <p>
                                    <form action="{% url 'quiz:quiz-pop-reviewer' object.pk %}" method="post">
                                        {% csrf_token %}
                                        <input class="btn btn-warning btn-xs" type="submit" value="{% trans "I don't want to review this Quiz anymore" %}">
                                    </form>
                                </p>
                                <p>
                                    <a href="{% url 'quiz:quiz-comment' object.pk %}" class="btn btn-primary" role="button"><span class="fa fa-comments-o"></span> {% trans 'Comment' %}</a>
                                </p>
                                <p>
                                    <a href="{% url 'quiz:quiz-review' object.pk %}" class="btn btn-success" role="button"><span class="fa fa-check"></span> {% trans 'Review' %}</a>
                                </p>
                            {% endif %}
                            {% if object.state == 'published' and object.has_questions %}
                                <p>
                                    <a href="{% url 'quiz:quiz-take' object.pk %}" class="btn btn-primary" role="button"><span class="fa fa-play"></span> {% trans 'Take' %}</a>
                                </p>
                            {% endif %}
                        {% include 'quiz/quiz_authors.html' with authors=object.authors.all only %}
                        <p><strong>{% trans 'Created' %} : </strong>{{ object.created|date:"DATETIME_FORMAT" }}</p>
                        <p><strong>{% trans 'Last Modified' %} : </strong>{{ object.modified|date:"DATETIME_FORMAT" }}</p>
                        {% if object.pub_date %}
                            <p><strong>{% trans 'Published' %} : </strong>{{ object.pub_date|date:"DATETIME_FORMAT" }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

quiz/templates/quiz/quiz_explanation.html
{% load i18n %}

<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">{% trans 'Explanation' %}</h3>
    </div>
    <div class="panel-body">
        {{ explanation|safe }}
    </div>
</div>

quiz/templates/quiz/quiz_user_list.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load url from future %}

{% block head_title %}
    {% trans 'Quizzes list' %}
{% endblock %}

{% block breadcrumbs %}
    <li class="active">{% trans 'Quiz Submission' %}</li>
{% endblock %}

{% block content %}
    <br>
    <div class='container'>
        <p>
            <a href="{% url 'quiz:quiz-create' %}" class="btn btn-primary" role="button">
                <span class="fa fa-plus"></span> {% trans 'Add a new quiz' %}
            </a>
        </p>
        <div class="endless_page_template">
            {% include 'quiz/quiz_user_list_page.html' %}
        </div>
    </div>
{% endblock %}

{% block js %}
    <script src="{{ STATIC_URL }}endless_pagination/js/endless-pagination.js"></script>
    <script>$.endlessPaginate();</script>
{% endblock %}

quiz/templates/quiz/stats_by_topic.html
{% extends "base_breadcrumbs.html" %}

{% load i18n %}
{% load guardian_tags %}
{% load url from future %}

{% block head_title %}
    {% trans "Statistics for " %}{{ object }}
{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'quiz:quiz-stats' %}">{% trans "Statistics" %}</a></li>
    <li><a href="{% url 'quiz:quiz-stats-by-subfield' pk=object.field.pk %}">{{ object.field }}</a></li>
    <li class="active">{{ object }}</li>
{% endblock %}

{% block page_title %}
    <div class="container page-header">
        <h1>
            {% trans "Statistics for " %}{{ object }}
        </h1>
    </div>
{% endblock %}

{% block content %}
    <div class='container'>
        <p>
            {% trans "Color code" %}
            <span class="label label-success">{% trans "Right answers" %}</span>
            <span class="label label-warning">{% trans "No answer" %}</span>
            <span class="label label-danger">{% trans "Wrong answers" %}</span>
        </p>
        <div class="list-group">
            {% for topic, sittings in sittings_by_topic %}
                {% if sittings.count > 0 %}
                    <a href="{% url 'quiz:quiz-stats-by-quiz' pk=topic.pk %}" class="list-group-item">
                        <h4 class="list-group-item-heading">{{ topic }}</h4>
                        <div class="row">
                            <div class="col-sm-3">
                                {% trans "Number of quizzes passed : " %}{{ sittings.count }}<br />
                            </div>
                            <div class="col-sm-6">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" style="width: {{ sittings.overall_right_percentage }}%">
                                        <span class="sr-only">{{ sittings.overall_right_percentage }}% (right)</span>
                                        {{ sittings.overall_right_percentage }}%
                                    </div>
                                    <div class="progress-bar progress-bar-warning" style="width: {{ sittings.overall_unknown_percentage }}%">
                                        <span class="sr-only">{{ sittings.overall_unknown_percentage }}% (unknwon)</span>
                                        {{ sittings.overall_unknown_percentage }}%
                                    </div>
                                    <div class="progress-bar progress-bar-danger" style="width: {{ sittings.overall_wrong_percentage }}%">
                                        <span class="sr-only">{{ sittings.overall_wrong_percentage }}% (wrong)</span>
                                        {{ sittings.overall_wrong_percentage }}%
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                            </div>
                        </div>

                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}