cytometry/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import FieldListView
from .views import SubFieldListView
from .views import TopicListView

urlpatterns = [
    url(r'^$', FieldListView.as_view(), name='field-list'),
    url(r'^(?P<slug>[-_\w]+)/$', SubFieldListView.as_view(), name='subfield-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)$', TopicListView.as_view(), name='topic-list'),
]

escca/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.cache import never_cache

from django.contrib import admin
from django.contrib.auth.decorators import login_required

from quiz.views import PPPView
from quiz.views import ProfileView
from quiz.views import ProfileUpdateView
from quiz.views import TopicResultsView
from quiz.views import UserTopicsView
from quiz.views import ContactView

from quiz.views import IndexView

from ckeditor import views

admin.autodiscover()
admin.site.site_header = _('ESCCA administration')
admin.site.site_title = _('ESCCA site admin')

urlpatterns = [
    # Examples:
    # url(r'^$', 'escca.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/profile/$', ProfileView.as_view(), name='profile'),
    url(r'^accounts/profile/topic/(?P<pk>\d+)$', TopicResultsView.as_view(), name='topic_results'),
    url(r'^accounts/profile/edit$', ProfileUpdateView.as_view(), name='profile_edit'),
    url(r'^accounts/profile/topics/edit$', UserTopicsView.as_view(), name='topics_edit'),
    url(r'^accounts/profile/ppp$', PPPView.as_view(), name='ppp'),
    url(r'^contact$', ContactView.as_view(), name='contact'),
    # We must override those urls in order to make them login_required instead of staff_required
    #url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(login_required(views.browse)), name='ckeditor_browse'),
    url(r'^quiz/', include('quiz.urls', namespace='quiz')),
    url(r'^cytometry/', include('cytometry.urls', namespace='cytometry')),
    url(r'^directory/', include('directory.urls', namespace='directory')),
    url(r'^sponsors/', include('sponsors.urls', namespace='sponsors')),
    url(r'^lectures/', include('lectures.urls', namespace='lectures')),
    url(r'^tutorships/', include('tutorships.urls', namespace='tutorships')),
    url(r'^$', IndexView.as_view(), name='index'),

    url(r'^pages/', include('django.contrib.flatpages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lectures/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import AttendeeCreateView
from .views import LectureCreateView
from .views import LectureDetailView
from .views import LectureDeleteView
from .views import LectureUpdateView
from .views import LectureUserListView
from .views import SessionListView
from .views import QuizAttachView
from .views import QuizDetachView
from .views import PreQuizTakeView
from .views import PostQuizTakeView
from .views import PostQuizResultView
from .views import QuizTeacherResultsView
from .views import SessionCreateView
from .views import SessionDeleteView
from .views import SessionUpdateView
from .views import TeacherCreateView
from .views import TeacherDeleteView


urlpatterns = [
    url(r'^$',
        SessionListView.as_view(), name='session-list'),
    url(r'^user_list$',
        LectureUserListView.as_view(), name='lecture-list'),
    url(r'^create$',
        LectureCreateView.as_view(), name='lecture-create'),
    url(r'^(?P<pk>\d+)/$',
        LectureDetailView.as_view(), name='lecture-detail'),
    url(r'^(?P<pk>\d+)/update/$',
        LectureUpdateView.as_view(), name='lecture-update'),
    url(r'^(?P<pk>\d+)/delete/$',
        LectureDeleteView.as_view(), name='lecture-delete'),
    url(r'^(?P<pk>\d+)/session/add$',
        SessionCreateView.as_view(), name='session-create'),
    url(r'^(?P<pk>\d+)/teacher/add$',
        TeacherCreateView.as_view(), name='teacher-create'),
    url(r'^(?P<pk>\d+)/quiz/add$',
        QuizAttachView.as_view(), name='quiz-attach'),
    url(r'^(?P<lecture>\d+)/teacher/(?P<pk>\d+)/delete/$',
        TeacherDeleteView.as_view(), name='teacher-delete'),
    url(r'^(?P<lecture>\d+)/quiz/(?P<pk>\d+)/delete/$',
        QuizDetachView.as_view(), name='quiz-detach'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<session>\d+)/quiz/(?P<pk>\d+)/pretake/$',
        PreQuizTakeView.as_view(), name='prequiz-take'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<session>\d+)/quiz/(?P<pk>\d+)/posttake/$',
        PostQuizTakeView.as_view(), name='postquiz-take'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<session>\d+)/quiz/(?P<pk>\d+)/result/$',
        PostQuizResultView.as_view(), name='quiz-result'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<session>\d+)/quiz/(?P<pk>\d+)/teacherresults/$',
        QuizTeacherResultsView.as_view(), name='quiz-teacher-results'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<pk>\d+)/delete/$',
        SessionDeleteView.as_view(), name='session-delete'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<pk>\d+)/update/$',
        SessionUpdateView.as_view(), name='session-update'),
    url(r'^(?P<lecture>\d+)/sessions/(?P<pk>\d+)/attendee/add/$',
        AttendeeCreateView.as_view(), name='attendee-create'),
]

quiz/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import GeneralStatsView
from .views import StatsBySubFieldView
from .views import StatsByTopicView
from .views import StatsByQuizView
from .views import StatsByQuestionView

from .views import QuizCreateView
from .views import QuizUpdateView

from .views import QuizListView
from .views import QuizUserListView
from .views import QuizReviewListView
from .views import QuizByTopicListView
from .views import QuizDetailView
from .views import QuizTakeView
from .views import QuizResultView

from .views import QuizAskReviewView
from .views import QuizAddReviewerView
from .views import QuizPopReviewerView
from .views import QuizCommentView
from .views import QuizReviewView
from .views import QuizPublishView
from .views import QuizArchiveView

from .views import MailToUsersView

urlpatterns = [
    url(r'^$', QuizListView.as_view(), name='quiz-list'),
    url(r'^stats/$', GeneralStatsView.as_view(), name='quiz-stats'),
    url(r'^stats/by_subfield/(?P<pk>\d+)$', StatsBySubFieldView.as_view(), name='quiz-stats-by-subfield'),
    url(r'^stats/by_topic/(?P<pk>\d+)$', StatsByTopicView.as_view(), name='quiz-stats-by-topic'),
    url(r'^stats/by_quiz/(?P<pk>\d+)$', StatsByQuizView.as_view(), name='quiz-stats-by-quiz'),
    url(r'^stats/by_question/(?P<pk>\d+)$', StatsByQuestionView.as_view(), name='quiz-stats-by-question'),
    url(r'^review/$', QuizReviewListView.as_view(), name='quiz-review-list'),
    url(r'^user/$', QuizUserListView.as_view(), name='quiz-user-list'),
    url(r'^(?P<fieldslug>[-_\w]+)/(?P<subfieldslug>[-_\w]+)/(?P<topicslug>[-_\w]+)/$',
        QuizByTopicListView.as_view(), name='quiz-by-topic-list'),
    url(r'^create$', QuizCreateView.as_view(), name='quiz-create'),
    url(r'^(?P<pk>\d+)/$', QuizDetailView.as_view(), name='quiz-detail'),
    url(r'^(?P<pk>\d+)/update$', QuizUpdateView.as_view(), name='quiz-update'),
    url(r'^(?P<pk>\d+)/ask_review$', QuizAskReviewView.as_view(), name='quiz-ask-review'),
    url(r'^(?P<pk>\d+)/add-reviewer$', QuizAddReviewerView.as_view(), name='quiz-add-reviewer'),
    url(r'^(?P<pk>\d+)/pop-reviewer$', QuizPopReviewerView.as_view(), name='quiz-pop-reviewer'),
    url(r'^(?P<pk>\d+)/comment$', QuizCommentView.as_view(), name='quiz-comment'),
    url(r'^(?P<pk>\d+)/review$', QuizReviewView.as_view(), name='quiz-review'),
    url(r'^(?P<pk>\d+)/publish$', QuizPublishView.as_view(), name='quiz-publish'),
    url(r'^(?P<pk>\d+)/archive$', QuizArchiveView.as_view(), name='quiz-archive'),
    url(r'^(?P<pk>\d+)/take$', QuizTakeView.as_view(), name='quiz-take'),
    url(r'^(?P<pk>\d+)/result$', QuizResultView.as_view(), name='quiz-result'),
    url(r'^mail_to_users/$', MailToUsersView.as_view(), name='mail_to_users'),
]

sponsors/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from .views import SponsorDetailView
from .views import SponsorListView


urlpatterns = [
    url(r'^$', SponsorListView.as_view(), name='sponsor-list'),
    url(r'^(?P<pk>\d+)$', SponsorDetailView.as_view(), name='sponsor-detail'),
]

templates/base.html
{% load raven %}
{% load staticfiles %}
{% load url from future %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block head_title %}{% endblock %}</title>
        <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block extra_head %}
        {% endblock %}

        <!-- Bootstrap -->
        {% comment %}
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        {% endcomment %}
        <link rel="stylesheet" href='{% static 'css/bootstrap.min.css' %}'>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
        <link rel="stylesheet" href='{% static 'css/default.css' %}' type='text/css'>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggle" data-target="#navbar-collapse-top" data-toggle="collapse" type="button">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="escca-brand navbar-brand" href="{% url 'index' %}">
                        <img alt='{% trans 'escca logo' %}' src='{% static 'img/logo_escca.png' %}'>
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbar-collapse-top">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Quiz" %} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'quiz:quiz-list' %}">{% trans 'Dashboard' %}</a></li>
                                <li><a href="{% url 'cytometry:field-list' %}">{% trans 'Browse by topic' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'quiz:quiz-user-list' %}">{% trans 'Quiz Submission' %}</a></li>
                                <li><a href="{% url 'quiz:quiz-review-list' %}">{% trans 'Help reviewing quizzes' %}</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Courses" %} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'lectures:session-list' %}">{% trans 'Courses' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'lectures:lecture-create' %}">{% trans 'Organize a course' %}</a></li>
                                <li><a href="{% url 'lectures:lecture-list' %}">{% trans 'My courses' %}</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans "Tutorings" %} <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'tutorships:tutorship-list' %}">{% trans 'Tutorings' %}</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url 'tutorships:tutorship-create' %}">{% trans 'Request a tutoring' %}</a></li>
                                {% if perms.tutorships.change_tutorship %}
                                    <li class="divider"></li>
                                    <li><a href="{% url 'tutorships:tutorship-committee-list' %}">{% trans 'Scientific committee panel' %}</a></li>
                                {% endif %}
                            </ul>
                        </li>
                        <li><a href="{% url 'directory:index' %}">{% trans 'Directory' %}</a></li>
                    </ul>
                    {% if user.is_authenticated %}
                        <p class="navbar-text navbar-right">{% trans 'Signed in as ' %}<a href="/accounts/profile/" class="navbar-link">{{ user.username }}</a></p>
                        <a class="btn btn-danger navbar-btn navbar-right" href="{% url 'account_logout' %}">{% trans 'Log out' %}</a>
                    {% else %}
                        <a class="btn btn-primary navbar-btn navbar-right" href="{% url 'account_login' %}">{% trans 'Log in' %}</a>
                    {% endif %}
                </div>
            </div>
        </nav>
        {% block body %}
            {% block breadcrumb %}{% endblock %}
            {% if messages %}
                <br>
                <div class="container">
                    {% for message in messages %}
                        <div class='alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissable'>
                            <button type='button' class='close' data-dismiss='alert' aria-hidden='true'>&times;</button>
                            <strong>{{message}}</strong>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            {% block page_title %}{% endblock %}
            {% block content %}{% endblock %}
        {% endblock %}

        {% block footer %}
            <nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button class="navbar-toggle" data-target="#navbar-collapse-bottom" data-toggle="collapse" type="button">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse" id="navbar-collapse-bottom">
                        <ul class="nav navbar-nav">
                            <li class="dropdown">
                                <li><a href="http://escca.eu" target="_blank">&copy; ESCCA 2014</a></li>
                                <li><a href="/pages/help/">{% trans "Help" %}</a></li>
                                <li><a href="/pages/about-us/">{% trans "About" %}</a></li>
                                <li><a href="{% url 'quiz:quiz-stats' %}">{% trans "Statistics" %}</a></li>
                                <li><a href="{% url 'contact' %}">{% trans "Contact" %}</a></li>
                                {% if user.is_superuser %}
                                    <li><a href="{% url 'quiz:mail_to_users' %}">{% trans "Send a mail to all users" %}</a></li>
                                {% endif %}
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a target="_blank" href="http://www.openscop.fr" class="openscop-brand">
                                    {% trans "Made by " %}
                                    <img alt="openscop" src="{% static 'img/logo_openscop.png' %}">
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        {% endblock %}
        <script src="//cdn.ravenjs.com/1.1.16/native/raven.min.js"></script>
        {% block js %}
        {% endblock %}
        <script>Raven.config('{% sentry_public_dsn %}').install();</script>
    </body>
</html>

templates/base_breadcrumbs.html
{% extends "base.html" %}

{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block breadcrumb %}
    <br>
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'index' %}">{% trans "Home" %}</a></li>
            {% block breadcrumbs %}{% endblock %}
        </ol>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% load url from future %}
{% load staticfiles %}

{% block head_title %}{% trans "TYsCCA" %}{% endblock %}

{% block content %}
    <div id="carousel-example-generic" class="carousel" data-ride="carousel">
        <div class="carousel-inner hidden-xs">
            <img alt="{% trans 'index background' %}" src="{% static 'img/index_background.jpg' %}">
            <div class="carousel-caption">
                <img alt="tyscca logo" src="{% static 'img/logo_tyscca_v2_wh.png' %}"><br>
                <h1>Test Yourself on Clinical Cell Analysis</h1>
            </div>
        </div>
        <div class="carousel-inner visible-xs">
            <img alt="{% trans 'index background' %}" src="{% static 'img/index_background_xs.jpg' %}">
            <div class="carousel-caption">
                <h1>Test Yourself on Clinical Cell Analysis</h1>
            </div>
        </div>
    </div>
    <div class="container homepage">
        <div class="row">
            <div class="col-sm-4">
                {% if user.is_authenticated %}
                    <a href="{% url 'quiz:quiz-list' %}" class="btn btn-block" role="button" data-toggle="tooltip" data-placement="top" title="{% trans "All quizzes that belong to the topics you're interested in are here!" %}">
                        <img alt="{% trans 'Dashboard' %}" src="{% static 'img/dashboard_ic.png' %}">
                        <h1 class="text-center">{% trans 'Dashboard' %}</h1>
                    </a>
                {% else %}
                    <a href="{% url 'account_login' %}" class="btn btn-block" role="button">
                        <h1 class="text-center"><span class="fa fa-sign-in"></span></h1>
                        <h1 class="text-center">{% trans 'Sign In' %}</h1>
                    </a>
                {% endif %}
            </div>
            <div class="col-sm-4">
                <a href="{% url 'cytometry:field-list' %}" class="btn btn-block" role="button" data-toggle="tooltip" data-placement="top" title="{% trans "Browse quizzes by topics" %}">
                    <img alt="{% trans 'Quizzes' %}" src="{% static 'img/quizzes_ic.png' %}">
                    <h1 class="text-center">{% trans 'Quizzes' %}<small>{% trans " / Fields" %}</small></h1>
                </a>
            </div>
            <div class="col-sm-4">
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="btn btn-block" role="button" data-toggle="tooltip" data-placement="top" title="{% trans "Manage your Profile and check the results of the quizzes you passed" %}">
                        <img alt="{% trans 'Profile' %}" src="{% static 'img/profile_ic.png' %}">
                        <h1 class="text-center">{% trans 'Profile' %}</h1>
                    </a>
                {% else %}
                    <a href="{% url 'account_signup' %}" class="btn btn-block" role="button">
                        <h1 class="text-center"><span class="fa fa-edit"></span></h1>
                        <h1 class="text-center">{% trans 'Sign Up' %}</h1>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% if sponsors.count > 0 %}
        <div class="container-fixed sponsors">
            <div class="row">
                <h3 class="text-center">{% trans 'Our sponsors' %}</h3>
                {% for sponsor in sponsors %}
                    <div class="col-sm-{{ sponsor_columns }}">
                        <a href="{% url 'sponsors:sponsor-detail' pk=sponsor.pk %}">
                            <img src="{{ sponsor.logo.url }}" alt="{{ sponsor }}" class="img-responsive center-block" height="100px" width="100px"></img>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function() {
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        });
    </script>
{% endblock %}

templates/paginator.html
{% load endless %}

{% get_pages %}

{% if pages.paginated %}
    <div class="container">
        <nav>
            <ul class="pagination">
                {% if pages.previous %}
                    <li>{{ pages.previous }}</li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}

                {% for page in pages %}
                    {% if page.is_current %}
                        <li class="active">{{ page }}</li>
                    {% else %}
                        <li>{{ page }}</li>
                    {% endif %}
                {% endfor %}

                {% if pages.next %}
                    <li>{{ pages.next }}</li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}

templates/ppp.html
{% extends "easy_pdf/base.html" %}

{% load staticfiles %}

{% block layout_style %}
    <style type="text/css">
        @page {
            size: {{ pagesize|default:"A4" }};
            margin-left: 5.5cm;
            margin-right: 2.5cm;
            margin-top: 2.5cm;
            margin-bottom: 2cm;

            @frame header {
                -pdf-frame-content: page-header;
                margin-top: 1.3cm;
                margin-right: 2mm;
                margin-bottom: 1cm;
                margin-left: 1.2cm;
            }
        }
    </style>
{% endblock %}

{% block extra_style %}
    <style type="text/css">
        html {
            font-family: "Lato", "Helvetica", "sans-serif";
            color: #333333;
        }

        p {
            margin: 0 0 6px 0;
            font-size: 11pt;
            font-family: "Lato", "Helvetica", "sans-serif";
        }

        table {
            line-height: 140%;
            margin-bottom: 20px;
        }

        table.bordered {
            border-top: 0.1pt solid #999999;
            border-bottom: 0.1pt solid #999999;
        }

        tr, td, th { border: none; }

        th {
            font-size: 10pt;
            border-bottom: 0.1pt solid #999999;
            padding: 3px 0;
            line-height: 1;
            font-weight: bold;
        }

        td {
            font-size: 10pt;
            font-family: "Lato", "Helvetica", "sans-serif";
            vertical-align: top;
            padding: 3px 0;
        }

        td:last-child { padding-bottom: 0; }

        .text-left { text-align: left; }
        .text-right { text-align: right; }
        .bottom-10 { margin-bottom: 10px; }
        .bottom-20 { margin-bottom: 20px; }
        .bottom-100 { margin-bottom: 170px; }
        .background {

        }

        .header { color: #7f7f7f; }
        .header p { font-size: 13px; line-height: 1.5em; }
        .header-link { font-weight: bold; text-decoration: none; color: #E90D71; font-size: 14px; }
        .logo {
            margin-bottom: 20px;
            margin-left: -25px;
        }
        .logo img { 
            zoom: 60%;
        }
        .logo2 { 
            padding-top: -25px;
            padding-left: 45px;
            margin-bottom: 20px;
            margin-left: -25px;
        }
        .logo2 img {
            zoom: 40%;
        }

        .recipient { margin-left: 7cm; }

        .main h1 {
            padding-top: 150px;
            margin: 18px 0 18px 0;
            font-size: 300%;
            font-weight: normal;
            color: #E90D71;
        }

        .main h2 {
            margin: 18px 0 6px 0;
            font-size: 180%;
            font-weight: normal;
        }

        .info { border: 1px solid #E90D71; padding: 10px; margin-top: 50px; margin-bottom: 50px; }
        .info a { color: #E90D71; text-decoration: none; }

    </style>
{% endblock %}

{%block page_header%}
    <div id="page-header">
        <div class="header">
            <p class="logo"><img src="http://tyscca.eu/static/img/escca.jpg"></p>
            <p class="header-link">
                <a class="header-link" href="http://escca.eu">escca.eu</a>
            </p>
            <p class="header">Registered with the Chamber of Commerce</p>
            <p class="header">at Rotterdam (NL) under # 24 32 61 94</p>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div id="content">
        <div class="recipient bottom-10">
            <p class="logo2"><img src="http://tyscca.eu/static/img/logo_tyscca_v2.png"></p>
            <p class="header-link" style="padding-left:45px;padding-top:3px;">
                <a class="header-link" href="http://tyscca.eu">tyscca.eu</a>
            </p>
        </div>
        <div class="main">
            <h1>ESCCA Certificate</h1>
            {% comment %}
            <img src="static/img/escca_background.png" class="background">
            {% endcomment %}

            <p class="info">
                Competences and continuous Education.<br>
                Contribution to development and Education in Cell Analysis
            </p>

            <h2>
                {{ user.first_name|title }} {{ user.last_name|title }}
                {% if user.profile.lab_name %}
                    {% if user.profile.lab_name_url %}
                        - <a href="{{ user.profile.lab_name_url }}">{{ user.profile.lab_name }}</a>
                    {% else %}
                        - {{ user.profile.lab_name }}
                    {% endif %}
                {% endif %}
            </h2>
            <small>TySCCA ID : {{ user.profile.get_tyscca_id }}</small>
            <p></p>


            <table class="bordered bottom-100">
                <tr>
                    <td class="item-name"><strong>ESCCA points acquired for quiz results</strong></td>
                    <td><strong>{{ user.sitting_set.only_best_scores.overall_score }}</strong></td>
                </tr>
                <tr>
                    <td class="item-name"><strong>ESCCA points acquired for collaboration</strong></td>
                    <td><strong>{{ user.profile.get_collaboration_points }}</strong></td>
                </tr>
            </table>

            <p>Saint-Étienne, on {{ today|date:"F jS Y" }}</p>
            <p>Claude Lambert</p>
            <p class="bottom-20">
                <img src="http://tyscca.eu/static/img/claude_lambert_signature.jpg" height="49" width="100">
            </p>
            <p>TySCCA Coordinator</p>
        </div>
    </div>
{% endblock %}